Fix \n in regex sanitizer

diff --git a/amlgrep b/amlgrep
--- a/amlgrep
+++ b/amlgrep
@@ -45,20 +45,14 @@ set -eu
 DIE () { echo "$0: ERROR: $*" >&2; exit 1; }
 WARN () { echo "$0: WARNING: $*" >&2; }
 
-case $BASH_VERSION in
-    4.*)
-        shopt -s compat31
-        newline='\n'
-        ;;
-    3.*)
-        newline='\\n'
-        ;;
-    [12].*)
-        WARN "This script probably doesn't work very well with bash-2.x"
-        ;;
-esac
+newline='\\n'
+test_rs='\n\n'
+[[ $test_rs =~ $newline ]] &&
+    [ "${BASH_REMATCH[0]}" = '\n' ] ||
+    DIE "INTERNAL ERROR: bash [[ =~ ]] doesn't work as expected"
 
-sedver=$(sed --version 2>&1)
+
+sedver=$(sed --version 2>&1 || true)
 if [[ $sedver =~ GNU ]]
 then
     sed () { command sed -r "$@"; }
@@ -93,12 +87,12 @@ sanitize_pattern () {
 # make it's semantics consistent with hmlgrep and pymlgrep.
 sanitize_pattern_RS () {
     local pattern="$1"
-    if [[ $pattern =~ "(^|\||\()[$newline\^]" ]]
+    if [[ $pattern =~ (^|\||\()($newline|\^) ]]
     then
         sanitize_pattern "$pattern"
     else
         sanitize_pattern "$pattern" |
-            sed -e 's@^@\\n(\n|[:print:])*(@g' \
+            sed -e 's@^@\\n[[:print:]]*(@g' \
                 -e 's@$@)@g'
     fi
 }
